language: php
sudo: false

php:
  - 7.1
  - 7.2
  
env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update $PREFER_LOWEST

script:
  - composer test

after_success:
 - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
 - php php-coveralls.phar -v

notifications:
  email: false
